import Navbar from "@/components/navigation/Navbar";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inclusive_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

const inclusive_sans = Inclusive_Sans({ weight:"400",subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nana Kwasi Asante",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inclusive_sans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="max-w-[900px] pt-[8vh] mx-auto p-5 lg:px-0">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
